# docker build -t d:1 -f Dockerfile_5_6 ./
# docker run -it --rm -p 8000:80 d:1
# docker container inspect [id] | grep Health

FROM nginx:latest

HEALTHCHECK --interval=10s --timeout=3s CND curl -f http://localhost/ || exit 1