# docker build -t d:1 -f Dockerfile_5_5 ./
# docker run -it --rm -p 8000:80 d:1

FROM ubuntu:jammy

RUN ["apt","update", "-y"]
RUN ["apt-get","update","-y"]
RUN ["apt-get","install","-y","tzdata"]
RUN ["apt-get","install","-y", "python3","python3-pip"]
RUN ["apt","install", "-y","nginx"]
RUN ["apt-get","install","-y","ufw"]
RUN ["ufw","allow","Nginx HTTP"]
RUN ["apt","install","-y","curl"]

ADD index.html /var/www/html

CMD ["nginx","-g","daemon off;"]